package: emit pacman-compatible SDK archives

diff --git a/vita-makepkg b/vita-makepkg
--- a/vita-makepkg
+++ b/vita-makepkg
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 #   makepkg - make packages compatible for use with pacman
 #   @configure_input@
@@ -44,7 +44,7 @@ unset CDPATH
 # Ensure GREP_OPTIONS doesn't screw with our grep calls
 unset GREP_OPTIONS
 
-declare -r makepkg_version='@PACKAGE_VERSION@'
+declare -r makepkg_version='1.0.0'
 declare -r confdir="$DIR"
 declare -r BUILDSCRIPT='VITABUILD'
 declare -r startdir="$PWD"
@@ -167,8 +167,13 @@ clean_up() {
 }
 
 enter_fakeroot() {
-	msg "$(gettext "Entering %s environment...")" "fakeroot"
-	fakeroot -- $0 -F "${ARGLIST[@]}" || exit $?
+	if type -p fakeroot >/dev/null; then
+		msg "$(gettext "Entering %s environment...")" "fakeroot"
+		fakeroot -- "$0" -F "${ARGLIST[@]}" || exit $?
+	else
+		msg "$(gettext "Entering %s environment...")" "rootless packaging"
+		FAKEROOTKEY=vita-makepkg-rootless "$0" -F "${ARGLIST[@]}" || exit $?
+	fi
 }
 
 # Automatically update pkgver variable if a pkgver() function is provided
@@ -608,7 +613,6 @@ write_kv_pair() {
 }
 
 write_pkginfo() {
-	local builddate=$(date -u "+%s")
 	if [[ -n $PACKAGER ]]; then
 		local packager="$PACKAGER"
 	else
@@ -622,19 +626,14 @@ write_pkginfo() {
 
 	msg2 "$(gettext "Generating %s file...")" ".PKGINFO"
 	printf "# Generated by makepkg %s\n" "$makepkg_version"
-	printf "# using %s\n" "$(fakeroot -v)"
-	printf "# %s\n" "$(LC_ALL=C date -u)"
+	printf "# Generated by vita-makepkg\n"
 
 	write_kv_pair "pkgname" "$pkgname"
-	if (( SPLITPKG )) || [[ "$pkgbase" != "$pkgname" ]]; then
-		write_kv_pair "pkgbase" "$pkgbase"
-	fi
+	write_kv_pair "pkgbase" "$pkgbase"
+	write_kv_pair "xdata" "pkgtype=pkg"
 
 	local fullver=$(get_full_version)
 	write_kv_pair "pkgver" "$fullver"
-	if [[ "$fullver" != "$basever" ]]; then
-		write_kv_pair "basever" "$basever"
-	fi
 
 	# TODO: all fields should have this treatment
 	local spd="${pkgdesc//+([[:space:]])/ }"
@@ -643,13 +642,19 @@ write_pkginfo() {
 
 	write_kv_pair "pkgdesc" "$spd"
 	write_kv_pair "url" "$url"
-	write_kv_pair "builddate" "$builddate"
+	write_kv_pair "builddate" "$SOURCE_DATE_EPOCH"
 	write_kv_pair "packager" "$packager"
 	write_kv_pair "size" "$size"
 	write_kv_pair "arch" "$pkgarch"
 
-	mapfile -t provides < <(find_libprovides)
-	mapfile -t depends < <(find_libdepends)
+	provides=()
+	while IFS= read -r value; do
+		provides+=("$value")
+	done < <(find_libprovides)
+	depends=()
+	while IFS= read -r value; do
+		depends+=("$value")
+	done < <(find_libdepends)
 
 	write_kv_pair "license"     "${license[@]}"
 	write_kv_pair "replaces"    "${replaces[@]}"
@@ -666,18 +671,40 @@ write_pkginfo() {
 write_buildinfo() {
 	msg2 "$(gettext "Generating %s file...")" ".BUILDINFO"
 
-	write_kv_pair "builddir"  "${BUILDDIR}"
+	write_kv_pair "format" "2"
+	write_kv_pair "pkgname" "$pkgname"
+	write_kv_pair "pkgbase" "$pkgbase"
+
+	local fullver=$(get_full_version)
+	write_kv_pair "pkgver" "$fullver"
+	write_kv_pair "pkgarch" "$pkgarch"
 
 	local sum="$(sha256sum "${BUILDFILE}")"
 	sum=${sum%% *}
 
 	write_kv_pair "pkgbuild_sha256sum" $sum
-
+	write_kv_pair "packager" "${PACKAGER:-Unknown Packager}"
+	write_kv_pair "builddate" "$SOURCE_DATE_EPOCH"
+	write_kv_pair "builddir" "${BUILDDIR}"
+	write_kv_pair "startdir" "${startdir}"
+	write_kv_pair "buildtool" "vita-makepkg"
+	write_kv_pair "buildtoolver" "$makepkg_version"
 	write_kv_pair "buildenv" "${BUILDENV[@]}"
 	write_kv_pair "options" "${OPTIONS[@]}"
+}
 
-	local pkglist=($(run_pacman -Q | sed "s# #-#"))
-	write_kv_pair "installed" "${pkglist[@]}"
+list_package_files() {
+	local excluded="$1"
+	local path
+
+	(
+		export LC_COLLATE=C
+		shopt -s dotglob nullglob
+		for path in *; do
+			[[ -n $excluded && $path = "$excluded" ]] && continue
+			printf '%s\0' "$path"
+		done
+	)
 }
 
 create_package() {
@@ -689,10 +716,24 @@ create_package() {
 		exit 1 # $E_MISSING_PKGDIR
 	fi
 
-	cd_safe "$pkgdir"
+	if [[ -z $VITASDK || $VITASDK != /* || $VITASDK = / ]]; then
+		error "$(gettext "%s must be an absolute, non-root path.")" "VITASDK"
+		exit 1
+	fi
+
+	local package_root="$pkgdir/${VITASDK#/}"
+	if [[ ! -d $package_root ]]; then
+		error "$(gettext "Package did not install under %s.")" "\$pkgdir\$VITASDK"
+		plain "$(gettext "Aborting...")"
+		exit 1
+	fi
+
+	cd_safe "$package_root"
 	msg "$(gettext "Creating package \"%s\"...")" "$pkgname"
 
 	pkgarch=$(get_pkg_arch)
+	write_pkginfo > .PKGINFO
+	write_buildinfo > .BUILDINFO
 
 	# tar it up
 	local fullver=$(get_full_version)
@@ -706,14 +747,30 @@ create_package() {
 	# the null string rather than itself
 	shopt -s nullglob
 
+	msg2 "$(gettext "Generating %s file...")" ".MTREE"
+	list_package_files .MTREE |
+		COPYFILE_DISABLE=1 LANG=C bsdtar -cf - --format=mtree \
+			--no-acls --no-fflags --no-mac-metadata --no-xattrs \
+			--options='!all,use-set,type,uid,gid,mode,time,size,sha256,link' \
+			--uid 0 --gid 0 --null --files-from - |
+		gzip -c -f -n > .MTREE || ret=$?
+
+	if (( ret )); then
+		error "$(gettext "Failed to create package metadata.")"
+		exit 1
+	fi
+
 	msg2 "$(gettext "Compressing package...")"
 	# TODO: Maybe this can be set globally for robustness
 	shopt -s -o pipefail
 	# bsdtar's gzip compression always saves the time stamp, making one
 	# archive created using the same command line distinct from another.
 	# Disable bsdtar compression and use gzip -n for now.
-	cd_safe "./$VITASDK/arm-vita-eabi"
-	LANG=C bsdtar -hcf - * |
+	list_package_files |
+	COPYFILE_DISABLE=1 LANG=C bsdtar -cf - \
+		--no-acls --no-fflags --no-mac-metadata --no-xattrs \
+		--uid 0 --gid 0 --uname root --gname root \
+		--null --files-from - |
 	case "$PKGEXT" in
 		*tar.gz)  ${COMPRESSGZ[@]:-gzip -c -f -n} ;;
 		*tar.bz2) ${COMPRESSBZ2[@]:-bzip2 -c -f} ;;
@@ -725,7 +782,7 @@ create_package() {
 		*) warning "$(gettext "'%s' is not a valid archive extension.")" \
 			"$PKGEXT"; cat ;;
 	esac > "${pkg_file}" || ret=$?
-	cd_safe "$pkgdir"
+	cd_safe "$package_root"
 
 	shopt -u nullglob
 	shopt -u -o pipefail
@@ -1389,6 +1446,8 @@ SRCEXT=${_SRCEXT:-$SRCEXT}
 GPGKEY=${_GPGKEY:-$GPGKEY}
 PACKAGER=${_PACKAGER:-$PACKAGER}
 CARCH=${_CARCH:-$CARCH}
+SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH:-$(date -u "+%s")}
+export SOURCE_DATE_EPOCH
 
 if (( ! INFAKEROOT )); then
 	if (( EUID == 0 )); then
@@ -1550,7 +1609,11 @@ if (( INFAKEROOT )); then
 		run_split_packaging
 	fi
 
-	msg "$(gettext "Leaving %s environment.")" "fakeroot"
+	if [[ $FAKEROOTKEY = vita-makepkg-rootless ]]; then
+		msg "$(gettext "Leaving %s environment.")" "rootless packaging"
+	else
+		msg "$(gettext "Leaving %s environment.")" "fakeroot"
+	fi
 	exit 0 # $E_OK
 fi
 
@@ -1621,6 +1684,8 @@ else
 	# clean existing pkg directory
 	if [[ -d $pkgdirbase ]]; then
 		msg "$(gettext "Removing existing %s directory...")" "\$pkgdir/"
+		chmod u+rwx "$pkgdirbase" 2>/dev/null || true
+		chmod -R u+w "$pkgdirbase" 2>/dev/null || true
 		rm -rf "$pkgdirbase"
 	fi
 	mkdir -p "$pkgdirbase"
